baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My site Hugo'
theme = 'tale'

[Author]
  name = "Aldo Javier Loayza"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "Contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[params]
css = ["css/estilos.css"]